ARG BASE_IMAGE=node:20.12-slim

################################################################################
# Use node image for base image for all stages.
FROM ${BASE_IMAGE} as base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable
COPY . /app
WORKDIR /app

FROM base as prod-deps
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --prod --frozen-lockfile

FROM base AS build
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile
RUN pnpm run build

FROM base
COPY --from=prod-deps /app/node_modules /app/node_modules
COPY --from=build /app/build /app/build

# WORKDIR /app
# COPY --from=build /app/build ./build/
# COPY --from=build /app/package*.json ./
# RUN npm i --omit=dev
EXPOSE 3000
ENV NODE_ENV=production
CMD [ "node", "build/index.js" ]